# title: Anastasiia Krokhina
# name: Anastasiia Krokhina
# email: a.krokhina@chemoinformatics.simplelogin.com
# description: >- # this means to ignore newlines until "baseurl:"
#   "Hello, my name is Anastasiia. I am chemist conducting research in chemoinfromatics and materials informatics. This is my web-page."
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "https://anastasiiakrokhina.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# github_username: AnastasiiaKrokhina
# linkedin_username: anastasiia-k-68154824b

# # Build settings
# theme: minimal-mistakes-jekyll
# plugins:
#   - jekyll-feed

# remote_theme: "mmistakes/minimal-mistakes"
# plugins:
#   - jekyll-include-cache


# # ------- SKIN --------
# minimal_mistakes_skin: "contrast" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"


title: Personal web-page
name: Anastasiia Krokhina
email: a.krokhina@chemoinformatics.simplelogin.com

description: >-
  Hello, my name is Anastasiia. I am a chemist conducting research in chemoinformatics and materials informatics. This is my webpage.

baseurl: ""
url: "https://anastasiiakrokhina.github.io"

github_username: AnastasiiaKrokhina
linkedin_username: anastasiia-k-68154824b

# Build settings
remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-feed
  - jekyll-include-cache

# Minimal Mistakes skin
minimal_mistakes_skin: "contrast"

author:
  name: "Anastasiia Krokhina"
  avatar: # optional, e.g. "/assets/images/profile.jpg"
  bio: "Chemoinformatics and materials informatics"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:a.krokhina@chemoinformatics.simplelogin.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/anastasiia-k-68154824b/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/AnastasiiaKrokhina"



# https://lexi-jones.github.io/website-creation/
# I used this guide to fix issue with feed in the footer
atom_feed:
  path: #blank (default)uses feed.xml
  hide: true #false (default)

search:  true
search_full_content: # true, false (default)
search_provider: #lunr (default), algolia, google



logo: ""
masthead_title: "My Custom Title"
